"use strict";

// Bundles the heroicons we use into renderer/icons.js as inline SVG strings,
// so the renderer needs no build step or network access.
// Run: node scripts/build_icons.js   (also wired as `npm run icons`)

const fs = require("node:fs");
const path = require("node:path");

const NEEDED = [
  "bolt",
  "signal-slash",
  "arrow-path",
  "minus",
  "x-mark",
  "chevron-down",
];

const dir = path.join(__dirname, "..", "node_modules", "heroicons", "24", "outline");
const out = {};

for (const name of NEEDED) {
  const file = path.join(dir, `${name}.svg`);
  const svg = fs.readFileSync(file, "utf8");
  const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
  out[name] = inner;
}

const js =
  `"use strict";\n` +
  `/* Auto-generated by scripts/build_icons.js from heroicons (MIT). Do not edit. */\n` +
  `window.HEROICONS = ${JSON.stringify(out, null, 2)};\n`;

fs.writeFileSync(path.join(__dirname, "..", "renderer", "icons.js"), js);
console.log(`icons.js written (${NEEDED.length} heroicons)`);
